version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket lambda-checklist-bucket --region us-east-2 --output-template-file outputTemplate.yaml --debug
artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml
